// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42f1fe39-2f71-4668-9528-412f5d4c047e"),
                            Author = "George Orwell",
                            Price = 10.99m,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("2ed0b8c5-3148-49df-adbc-d1f3a3380adc"),
                            Author = "George Orwell",
                            Price = 10.99m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("ec502ffd-a3ec-411a-9071-fa2122981d82"),
                            Author = "George Orwell",
                            Price = 11.99m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("72653917-c237-4fe5-a0c1-150e44691c3b"),
                            Author = "George Orwell",
                            Price = 12.99m,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("043a3287-d2f7-4b7c-bacb-73ddd86e42cd"),
                            Author = "George Orwell",
                            Price = 13.99m,
                            Title = "The Return of the King"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
